#!/bin/bash

read_html () {
  wget $1
  while read -r html_code; do 
	 if [$html_code == *'href="http"'*]

  if [ -e "$1" ]
    then
      count=0
      while read -r file_contents; do
        let  "count+=1"
        echo "$count $file_contents"
      done < "$1"
    else
	echo "This file does not exist"
  fi
};


while getopts ":n: :h" option; do
  case "${option}" in
    f)
	FILE="${OPTARG}"
	read_file_with_num "$FILE"
	let "counter+=1"
	;;
    h)
        echo "There are two options"
	echo "[No Option]: Prints the file contents" 
	echo "-n : List with numbers"
	echo "-h : prints help"
	let "counter+=1"
	;;
    *) 
        echo "Invalid selection $1"
	exit 1
	;;
    esac
done

if [ $counter == 0 ]
then
	read_file "$1"
else
	exit 0
fi
